config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#home'
  get 'about', to:'welcome#about'

  get 'admin', to:'welcome#admin'

  get 'gemstones', to:'welcome#gemstone'

  resources :tools
  resources :toolcategories
  resources :fjewelries
  resources :findings

  resources :admgemstones

end

app/models/fjewelry.rb
class Fjewelry < ActiveRecord::Base
	has_attached_file :fjewelry_img, styles: { fjewelry_index: "300x300>", fjewelry_show: "500x500>" }, default_url: "/images/:style/missing.png"
	 	
  	validates_attachment_content_type :fjewelry_img, content_type: /\Aimage\/.*\z/


	scope :jewelry_type, ->(jewelry_types) { where(:jewelry_type => jewelry_types) }
	JEWELRY_TYPES = [
		"Earrings",
		"Pendants",
		"Chains",
		"Bracelets",
		"Wedding Bands",
		"Solitaire Rings"
	]

	scope :metal, ->(metals) { where(:metal => metals) }
	METALS = [
		"10K Gold",
		"14K Gold",
		"18K Gold",
		"Tungsten"
	]

	scope :color, ->(colors) { where(:color => colors) }
	COLORS = [
		"Yellow",
		"White",
		"Pink",
		"Black",
		"Blue",
		"Bronze",
		"Grey"
	]

	scope :stone, ->(stones) { where(:stone => stones) }
	STONES = [
		"Cubic Zirconia",
		"Coloured Stone",
		"Diamond",
		"No Stone"
	]

	validates :jewelry_type, presence: true, length: {maximum:50}
	validates :metal, presence: true, length: {maximum:50}
	validates :color, presence: true, length: {maximum:50}
	validates :stone, presence: true, length: {maximum:50}
	
	validates_inclusion_of :jewelry_type, in: JEWELRY_TYPES
	validates_inclusion_of :metal, in: METALS
	validates_inclusion_of :color, in: COLORS
	validates_inclusion_of :stone, in: STONES

end

app/controllers/fjewelries_controller.rb
class FjewelriesController < ApplicationController
	before_action :find_fjewelry, only: [:edit, :update, :show, :destroy]
	before_action :just_admin, only: [:admin]
	has_scope :jewelry_type, type: :array
	has_scope :metal, type: :array
	has_scope :color, type: :array
	has_scope :stone, type: :array
layout "applicationfjewelry"
	def index
	
		@fjewelries = apply_scopes(Fjewelry).all
		render :layout => "applicationfjewelry"
	end

	def new
		@fjewelry=Fjewelry.new
		render layout: "applicationfjewelry"
	end

	def create
		@fjewelry=Fjewelry.new(fjewelry_params)
		if @fjewelry.save
			redirect_to fjewelries_path
		else
			render "new"
		end
	end

	def show
		#raise @fjewelries.inspect
		#Rails.logger.debug params.inspect
		#urun detay sayfasindayken sidebar da ki filtreleme calissin diye duzenleme yapildi
	
		#if params[:jewelry_type] || params[:metal] || params[:color] || params[:stone]
			#@fjewelries = apply_scopes(Fjewelry).all
			#redirect_to fjewelries_path(@fjewelries)
		#	render "index"
		#else
		#	@fjewelry=Fjewelry.find(params[:id])
		#end
	
		#if @fjewelries.nil? 
	    #	@fjewelries = apply_scopes(Fjewelry).all
	    #	flash.now[:alert] = "search again"
	    #	render "index"
  		#end
	end

	def edit
		#@fjewelry = Fjewelry.find(params[:id])
		#render layout: "applicationfjewelry"
	end

	def update
		#@fjewelry = Fjewelry.find(params[:id])
		if @fjewelry.update(fjewelry_params)
			flash[:notice] = "Finished Jewelry record was successfully updated!"
			redirect_to fjewelry_path(@fjewelry)
		else
			render 'edit'
		end
	end

	def destroy
		@fjewelry.destroy
		redirect_to fjewelries_path
	end
	
	private
	def fjewelry_params
		params.require(:fjewelry).permit(:title, :short_desc, :long_desc, :sku, :price, :jewelry_type, :metal, :color, :stone, :fjewelry_img)
	end

	def find_fjewelry
		@fjewelry=Fjewelry.find(params[:id])
	end

	def just_admin
  		authenticate_user!

	  if current_user.email=="info@europeandesign.ca"
	     return
	  else
	     redirect_to root_path # or whatever
	  end
	end
end

app/helpers/fjewelries_helper.rb
module FjewelriesHelper
end

app/views/fjewelries/_form.html.erb
<%= form_for fjewelry do |f| %>
<p>
	<%=  f.file_field :fjewelry_img %>
</p>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :short_desc %><br>
		<%= f.text_field :short_desc %>
	</p>
	<p>
		<%= f.label :long_desc %><br>
		<%= f.text_field :long_desc %>
	</p>
	<p>
		<%= f.label :sku, 'SKU' %><br>
		<%= f.text_field :sku %>
	</p>
	<p>
		<%= f.label :price %><br>
		<%= f.text_field :price %>
	</p>
	<p>
		<%= f.label :jewelry_type, 'Type' %><br>
		<%= f.select :jewelry_type, Fjewelry::JEWELRY_TYPES -%>
	</p>
	<p>
		<%= f.label :metal, 'Metal' %><br>
		<%= f.select :metal, Fjewelry::METALS %>
	</p>
	<p>
		<%= f.label :color, 'Color' %><br>
		<%= f.select :color, Fjewelry::COLORS %>
	</p>
	<p>
		<%= f.label :stone, 'Stone' %><br>
		<%= f.select :stone, Fjewelry::STONES %>
	</p>

	<p>
		<%= f.submit update ? "Update" : "Create Finished Jewelry"%>
	</p>

<% end %>

app/views/fjewelries/edit.html.erb
<div class="col-lg-2" style="padding: 2rem;">
</div>
<div class="col-lg-6">
<h1> Edit existing Finished Jewelry</h1>
<% if @fjewelry.errors.any? %>
<h2 style="color:red;">The following errors prevented the gemstone from getting created</h2>
<ul>
	<% @fjewelry.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
	<% end %>
</ul>
<% end %>

<%= render 'form', fjewelry: @fjewelry, update: true -%>
<%= link_to "Back to Finished Jewelry listing", fjewelries_path %>
</div>

app/views/fjewelries/index.html.erb
<div class="col-xs-12 col-sm-10 col-lg-10">

		<div class="col-xs-12 col-lg-12">

			<div id="banner001" class="row">

				<div class="thumbnail">

				<%= image_tag "pic2000x200v2.gif", :class => "group list-group-image" %>   

				</div>

			</div>

		</div>



	<div id="products" class="row">

	<%  if not(params[:jewelry_type].blank? && params[:metal].blank? && params[:color].blank? && params[:stone].blank?) %>

		<%  @fjewelries.each do |fjewelry| %>

				<div class="item  col-xs-12 col-lg-3">

					<a href="/fjewelries/<%= fjewelry.id %>">

						<div class="thumbnail">

						<%= image_tag fjewelry.fjewelry_img.url(:fjewelry_show), :class => "group list-group-image" %> 

						<div class="caption">

							<h4 class="group inner grid-group-item-heading">

								<%= fjewelry.sku %></h4>

							<h4 class="group inner grid-group-item-heading">

								<%= fjewelry.title %></h4>

							<h4 class="group inner grid-group-item-heading">

								<%= fjewelry.short_desc %></h4>

						</div>

					</div>

					</a>

				</div>



		<% end %>

			<% if current_user.try(:admin?) %>

			<%= link_to "Add Tool", new_fjewelry_path %>

			<% end %>

	<% else %>





	

				<div id="products" class="row">   



				<div class="item  col-xs-12 col-lg-3">

					<a href="/fjewelries?jewelry_type[]=Earrings">

					<div class="thumbnail">

						<%= image_tag "fjindex1_500x250.jpg", :class => "group list-group-image" %> 

						<div class="caption">

							<h4 class="group inner grid-group-item-heading">Earrings</h4>

						</div>

					</div>

					</a>

				</div>

				<div class="item  col-xs-12 col-lg-3">

					<a href="/fjewelries?jewelry_type[]=Pendants">

					<div class="thumbnail">

						<%= image_tag "fjindex2_500x250.jpg", :class => "group list-group-image" %> 

						<div class="caption">

							<h4 class="group inner grid-group-item-heading">Pendants</h4>

						</div>

					</div>

					</a>

				</div>

				<div class="item  col-xs-12 col-lg-3">

				<a href="/fjewelries?jewelry_type[]=Chains">

					<div class="thumbnail">

						<%= image_tag "fjindex3_500x250.jpg", :class => "group list-group-image" %> 

						<div class="caption">

							<h4 class="group inner grid-group-item-heading">Chains</h4>

						</div>

					</div>

					</a>

				</div>

				<div class="item  col-xs-12 col-lg-3">

				<a href="/fjewelries?jewelry_type[]=Bracelets">

					<div class="thumbnail">

						<%= image_tag "fjindex4_500x250.jpg", :class => "group list-group-image" %> 

						<div class="caption">

							<h4 class="group inner grid-group-item-heading">Bracelets</h4>

						</div>

					</div>

					</a>

				</div>

				<div class="item  col-xs-12 col-lg-3">

				<a href="/fjewelries?jewelry_type[]=Wedding+Bands">

					<div class="thumbnail">

						<%= image_tag "fjindex5_500x250.jpg", :class => "group list-group-image" %> 

						<div class="caption">

							<h4 class="group inner grid-group-item-heading">Wedding Bands</h4>

						</div>

					</div>

					</a>

				</div>

				<div class="item  col-xs-12 col-lg-3">

				<a href="/fjewelries?jewelry_type[]=Solitaire+Rings">

					<div class="thumbnail">

						<%= image_tag "fjindex6_500x250.jpg", :class => "group list-group-image" %> 

						<div class="caption">

							<h4 class="group inner grid-group-item-heading">Solitaire Rings</h4>

						</div>

					</div>

					</a>

				</div>

				

			</div>


<% end %>

</div>

</div>

app/views/fjewelries/new.html.erb
<div class="col-lg-2" style="padding: 2rem;">
</div>
<div class="col-lg-6">
<h1>Create a Finished Jewelry</h1>

<% if @fjewelry.errors.any? %>
<h2>The following errors prevented the finished jewelry record from getting created</h2>
<ul>
	<% @fjewelry.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
	<% end %>
</ul>
<% end %>

<%= render 'form', fjewelry: @fjewelry, update: false -%>

<%= link_to "Back to finished jewelry listing", fjewelries_path %>
</div>

app/views/fjewelries/show.html.erb
<div class="col-xs-10 col-lg-10">	

		<div class="col-xs-12 col-lg-12">
			<div id="banner001" class="row">
				<div class="thumbnail">
				<%= image_tag "pic2000x200v2.gif", :class => "group list-group-image" %>   
				</div>
			</div>
		<div>

	<div class="col-lg-6">

		<% if current_user.try(:admin?) %>
			<div class="col-lg-12">
			<%= link_to "Back", fjewelries_path %>
			<%= link_to "Edit", edit_fjewelry_path %>
			<%= link_to "Delete", fjewelry_path(@fjewelry), method: :delete, data: { confirm: "Are you sure?"} %>
			</div>
		<% end %>
		<div class="col-lg-12">
			<%= image_tag @fjewelry.fjewelry_img.url(:fjewelry_show) %>
		</div>

	</div>



	<div class="col-lg-6">
		<h2><span class="label label-primary"><%= @fjewelry.title %></span></h2><br>
		
		<h3><span class="xxxxxxxxxxxx"><%= @fjewelry.short_desc %></span></h3><br>
		<h3>No:<span class="monospaced"><%= @fjewelry.sku %></span></h3><br>

		<% if user_signed_in? %>
		<h3>Price:<span class="monospaced"> $<%= @fjewelry.price %></span></h3><br>
		<% end %>

		<p><span class="description"><%= @fjewelry.long_desc %></span></p><br>
		<h3><u>Specifications</u></h3><br>
		
		<% if @fjewelry.jewelry_type? %>
			<div class="col-xs-6"><h4> Type:</h4></div>
			<div class="col-xs-6"><h4><%= @fjewelry.jewelry_type %></h4></div>
		<% end %>

		<% if @fjewelry.metal? %>
			<div class="col-xs-6"><h4> Metal:</h4></div>
			<div class="col-xs-6"><h4><%= @fjewelry.metal %></h4></div>
		<% end %>
		<% if @fjewelry.color? %>
			<div class="col-xs-6"><h4> Color:</h4></div>
			<div class="col-xs-6"><h4><%= @fjewelry.color %></h4></div>
		<% end %>

		<% if @fjewelry.stone? %>
			<div class="col-xs-6"><h4> Stone:</h4></div>
			<div class="col-xs-6"><h4><%= @fjewelry.stone %></h4></div>
		<% end %>
		
		<p>To order <a href="tel:18005551212">please call 1-800-555-1212</a></p>
	</div>




</div>