config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#home'
  get 'about', to:'welcome#about'

  get 'admin', to:'welcome#admin'

  get 'gemstones', to:'welcome#gemstone'

  resources :tools
  resources :toolcategories
  resources :fjewelries
  resources :findings

  resources :admgemstones

end

app/models/tool.rb
class Tool < ActiveRecord::Base
	belongs_to :toolcategory
	has_attached_file :tool_img, styles: { tool_index: "300x300>", tool_show: "500x500>" }, default_url: "/images/:style/missing.png"
	has_attached_file :tool_img2, styles: { tool_index: "300x300>", tool_show: "500x500>" }, default_url: "/images/:style/missing.png"
  	
  	validates_attachment_content_type :tool_img, content_type: /\Aimage\/.*\z/
  	validates_attachment_content_type :tool_img2, content_type: /\Aimage\/.*\z/

end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
	before_action :find_tool, only: [:edit, :update, :show, :destroy]
	before_action :just_admin, only: [:new,:create,:edit, :update, :destroy]
	#def toolshome
	#	render :layout => "applicationtool"
	#end

	def index
		if params[:tcat1].blank?
			@tools=Tool.all.order("created_at DESC")
		else 
			if params[:tcat2].blank?
				@toolcategory_id = Toolcategory.where(level1: params[:tcat1]).ids
				@tools = Tool.where(:toolcategory_id => @toolcategory_id)
			else
				if params[:tcat3].blank?
				@toolcategory_id = Toolcategory.find_by(level1: params[:tcat1], level2: params[:tcat2]).id	
				@tools = Tool.where(:toolcategory_id => @toolcategory_id)
				else
				@toolcategory_id = Toolcategory.find_by(level1: params[:tcat1], level2: params[:tcat2],level3: params[:tcat3]).id	
				@tools = Tool.where(:toolcategory_id => @toolcategory_id)
				end
			end
			
		end
		#if user is admin render admin else tool
		render layout: "applicationtool"
	end

	def show
		#Rails.logger.debug params.inspect
		render layout: "applicationtool"
	end

	def new
		@tool=Tool.new
		@toolcategories=Toolcategory.all.order("level1, level2, level3").map{|tc| [tc.level1.to_s + " > " + tc.level2.to_s + " > " + tc.level3.to_s, tc.id] }
		render layout: "applicationtool"
	end

	def create
		@tool=Tool.new(tool_params)
		@tool.toolcategory_id=params[:toolcategory_id]
		if @tool.save
			redirect_to tools_path
		else
			render "new"
		end
	end

	def edit
		@toolcategories=Toolcategory.all.order("level1, level2, level3").map{|tc| [tc.level1.to_s + " > " + tc.level2.to_s + " > " + tc.level3.to_s, tc.id] }
		render layout: "applicationtool"
	end

	def update
		@tool.toolcategory_id=params[:toolcategory_id]
		if @tool.update(tool_params)
			redirect_to tools_path
		else
			render "edit"
		end
	end

	def destroy
		@tool.destroy
		redirect_to tools_path
	end

	private
	def tool_params
		params.require(:tool).permit(:title, :short_desc, :long_desc, :toolcategory_id, :tool_img, :tool_img2, :sku, :price, :brand, :weight, :height, :width, :color, :metal, :whatt, :measuringrange, :battery, :usedwith,:depth)
	end

	def find_tool
		@tool=Tool.find(params[:id])
	end

	def just_admin
  		authenticate_user!

	  if current_user.email=="info@europeandesign.ca"
	     return
	  else
	     redirect_to root_path # or whatever
	  end
	end


end

app/views/tools/_form.html.erb
<%=  simple_form_for @tool, :html => { :multipart => true } do |f| %>
<%=  select_tag(:toolcategory_id, options_for_select(@toolcategories), :prompt => "Select Category") %>
<%=  f.file_field :tool_img %>
<%=  f.file_field :tool_img2 %>
<%=  f.input :sku, label: "SKU" %>
<%=  f.input :title, label: "Tool Name" %>
<%=  f.input :short_desc, label: "Short Description" %>
<%=  f.input :long_desc, label: "Long Description" %>
<%=  f.input :price, label: "Price" %>
<%=  f.input :brand, label: "Brand Name" %>
<%=  f.input :weight, label: "Weight" %>
<%=  f.input :height, label: "Height" %>
<%=  f.input :width, label: "Width" %>
<%=  f.input :color, label: "Color" %>
<%=  f.input :metal, label: "Metal" %>
<%=  f.input :whatt, label: "WHATT" %>
<%=  f.input :measuringrange, label: "Measuring Range" %>
<%=  f.input :battery, label: "Battery" %>
<%=  f.input :usedwith, label: "Used With" %>
<%=  f.input :depth, label: "Depth" %>

<%=  f.button :submit, label: "Save" %>
<% end %>

app/views/tools/edit.html.erb
<div class="col-xs-12 col-sm-10 col-lg-10">
	<h2>Edit Tool</h2>
<%=  simple_form_for @tool, :html => { :multipart => true } do |f| %>
<%=  f.select :toolcategory_id, @toolcategories %>
<%=  f.file_field :tool_img %>
<%=  f.file_field :tool_img2 %>
<%=  f.input :sku, label: "SKU" %>
<%=  f.input :title, label: "Tool Name" %>
<%=  f.input :short_desc, label: "Short Description" %>
<%=  f.input :long_desc, label: "Long Description" %>
<%=  f.input :price, label: "Price" %>
<%=  f.input :brand, label: "Brand Name" %>
<%=  f.input :weight, label: "Weight" %>
<%=  f.input :height, label: "Height" %>
<%=  f.input :width, label: "Width" %>
<%=  f.input :color, label: "Color" %>
<%=  f.input :metal, label: "Metal" %>
<%=  f.input :whatt, label: "WHATT" %>
<%=  f.input :measuringrange, label: "Measuring Range" %>
<%=  f.input :battery, label: "Battery" %>
<%=  f.input :usedwith, label: "Used With" %>
<%=  f.input :depth, label: "Depth" %>
<%=  f.button :submit, label: "Save" %>
<% end %>
</div>

app/views/tools/index.html.erb
<div class="col-xs-12 col-sm-10 col-lg-10">
		<div class="col-xs-12 col-lg-12">
			<div id="banner001" class="row">
				<div class="thumbnail">
				<%= image_tag "pic2000x200v2.gif", :class => "group list-group-image" %>   
				</div>
			</div>
		</div>

	<div id="products" class="row">
	<%  if not(params[:tcat1].blank?) %>
		<%  @tools.each do |tool| %>
			<!-- <h2> <%=  link_to tool.title, tool_path(tool) %></h2> -->
				
				<div class="item  col-xs-12 col-lg-3">
					<a href="/tools/<%= tool.id %>">
						<div class="thumbnail">
						<%= image_tag tool.tool_img.url(:tool_show), :class => "group list-group-image" %> 
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">
								<%= tool.sku %></h4>
							<h4 class="group inner grid-group-item-heading">
								<%= tool.title %></h4>
							<h4 class="group inner grid-group-item-heading">
								<%= tool.short_desc %></h4>
						</div>
					</div>
					</a>
				</div>

		<% end %>
			<% if current_user.try(:admin?) %>
			<%= link_to "Add Tool", new_tool_path %>
			<% end %>
	<% else %>


	
		<div id="products" class="row">   
				<div class="item  col-xs-12 col-lg-3">
					<a href="/tools?tcat1=Abrasives"><div class="thumbnail">
						<%= image_tag "pic001.jpg", :class => "group list-group-image" %>   
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Abrasives</h4>
							<!--<p class="group inner grid-group-item-text">
								Product description... Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
								sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
							<divx class="row">
								<div class="col-xs-12 col-md-6">
									<p class="lead">
										$21.000</p>
								</div>
								<div class="col-xs-12 col-md-6">
									<a class="btn btn-success" href="http://www.europeandesign.ca">Add to cart</a>
								</div>
							</div>-->
						</div>
					</div></a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
					<a href="/tools?tcat1=Benches+%26+Accessories">
					<div class="thumbnail">
						<%= image_tag "pic004.jpg", :class => "group list-group-image" %> 
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Benches &amp; Accessories</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
					<a href="/tools?tcat1=Brushes">
					<div class="thumbnail">
						<%= image_tag "pic002.jpg", :class => "group list-group-image" %> 
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Brushes</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
				<a href="/tools?tcat1=Buffs">
					<div class="thumbnail">
						<%= image_tag "pic003.jpg", :class => "group list-group-image" %> 
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Buffs</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
				<a href="/tools?tcat1=Burs">
					<div class="thumbnail">
						<%= image_tag "pic004.jpg", :class => "group list-group-image" %> 
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Burs</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
				<a href="/tools?tcat1=Casting">
					<div class="thumbnail">
						<img class="group list-group-image" src="http://placehold.it/400x200/000/fff" alt="" />
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Casting</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
				<a href="/tools?tcat1=Cleaners">
					<div class="thumbnail">
						<img class="group list-group-image" src="http://placehold.it/400x200/000/fff" alt="" />
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Cleaners</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
				<a href="/tools?tcat1=Diamond+Tools+%26+Supplies">
					<div class="thumbnail">
						<img class="group list-group-image" src="http://placehold.it/400x200/000/fff" alt="" />
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Diamond Tools &amp; Supplies</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
				<a href="/tools?tcat1=Equipments">
					<div class="thumbnail">
						<img class="group list-group-image" src="http://placehold.it/400x200/000/fff" alt="" />
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Equipments</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
				<a href="/tools?tcat1=Drills">
					<div class="thumbnail">
						<img class="group list-group-image" src="http://placehold.it/400x200/000/fff" alt="" />
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Drills</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
				<a href="/tools?tcat1=Files">
					<div class="thumbnail">
						<img class="group list-group-image" src="http://placehold.it/400x200/000/fff" alt="" />
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Files</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
				<a href="/tools?tcat1=Gauges">
					<div class="thumbnail">
						<img class="group list-group-image" src="http://placehold.it/400x200/000/fff" alt="" />
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Gauges</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
				<a href="/tools?tcat1=Hammers">
					<div class="thumbnail">
						<img class="group list-group-image" src="http://placehold.it/400x200/000/fff" alt="" />
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Hammers</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
					<a href="/tools?tcat1=Hand+Forming">
					<div class="thumbnail">
						<img class="group list-group-image" src="http://placehold.it/400x200/000/fff" alt="" />
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Hand Forming</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
				<a href="/tools?tcat1=Lamps">
					<div class="thumbnail">
						<img class="group list-group-image" src="http://placehold.it/400x200/000/fff" alt="" />
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Lamps</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
				<a href="/tools?tcat1=Magnifiers+%26+Glasses">
					<div class="thumbnail">
						<img class="group list-group-image" src="http://placehold.it/400x200/000/fff" alt="" />
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Magnifiers &amp; Glasses</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
				<a href="/tools?tcat1=Plating">
					<div class="thumbnail">
						<img class="group list-group-image" src="http://placehold.it/400x200/000/fff" alt="" />
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Plating</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
				<a href="/tools?tcat1=Pilers+%26+Cutters">
					<div class="thumbnail">
						<img class="group list-group-image" src="http://placehold.it/400x200/000/fff" alt="" />
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Pilers &amp; Cutters</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
				<a href="/tools?tcat1=Polishing">
					<div class="thumbnail">
						<img class="group list-group-image" src="http://placehold.it/400x200/000/fff" alt="" />
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Polishing</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
				<a href="/tools?tcat1=Ring+Tools">
					<div class="thumbnail">
						<img class="group list-group-image" src="http://placehold.it/400x200/000/fff" alt="" />
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Ring Tools</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
				<a href="/tools?tcat1=Rolling+Mills">
					<div class="thumbnail">
						<img class="group list-group-image" src="http://placehold.it/400x200/000/fff" alt="" />
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Rolling Mills</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
				<a href="/tools?tcat1=Sawblades+%26+Sawframes">
					<div class="thumbnail">
						<img class="group list-group-image" src="http://placehold.it/400x200/000/fff" alt="" />
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Sawblades &amp; Sawframes</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
				<a href="/tools?tcat1=Scale+%26+Weights">
					<div class="thumbnail">
						<img class="group list-group-image" src="http://placehold.it/400x200/000/fff" alt="" />
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Scale &amp; Weights</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
				<a href="/tools?tcat1=Setting+%26+Engraving">
					<div class="thumbnail">
						<img class="group list-group-image" src="http://placehold.it/400x200/000/fff" alt="" />
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Setting &amp; Engraving</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
				<a href="/tools?tcat1=Soldering+Tools">
					<div class="thumbnail">
						<img class="group list-group-image" src="http://placehold.it/400x200/000/fff" alt="" />
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Soldering Tools</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
				<a href="/tools?tcat1=Store+Supplies">
					<div class="thumbnail">
						<img class="group list-group-image" src="http://placehold.it/400x200/000/fff" alt="" />
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Store Supplies</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
				<a href="/tools?tcat1=Testing+Tools">
					<div class="thumbnail">
						<img class="group list-group-image" src="http://placehold.it/400x200/000/fff" alt="" />
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Testing Tools</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
				<a href="/tools?tcat1=Tweezers">
					<div class="thumbnail">
						<img class="group list-group-image" src="http://placehold.it/400x200/000/fff" alt="" />
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Tweezers</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
				<a href="/tools?tcat1=Watch+Tools">
					<div class="thumbnail">
						<img class="group list-group-image" src="http://placehold.it/400x200/000/fff" alt="" />
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Watch Tools</h4>
						</div>
					</div>
					</a>
				</div>
				<div class="item  col-xs-12 col-lg-3">
				<a href="/tools?tcat1=Waxes">
					<div class="thumbnail">
						<img class="group list-group-image" src="http://placehold.it/400x200/000/fff" alt="" />
						<div class="caption">
							<h4 class="group inner grid-group-item-heading">Waxes</h4>
						</div>
					</div>
					</a>
				</div>
			</div>
	</div>
</div>

<% end %>
</div>
</div>

app/views/tools/new.html.erb
<div class="col-xs-12 col-sm-10 col-lg-10">

<%=  render "form" %>

</div>

app/views/tools/show.html.erb
<div class="col-xs-10 col-lg-10">	

		<div class="col-xs-12 col-lg-12">
			<div id="banner001" class="row">
				<div class="thumbnail">
				<%= image_tag "pic2000x200v2.gif", :class => "group list-group-image" %>   
				</div>
			</div>
		<div>

	<div class="col-lg-6">

		<% if current_user.try(:admin?) %>
			<div class="col-lg-12">
			<%= link_to "Back", tools_path %>
			<%= link_to "Edit", edit_tool_path %>
			<%= link_to "Delete", tool_path(@tool), method: :delete, data: { confirm: "Are you sure?"} %>
			</div>
		<% end %>
		<div class="col-lg-12">
			<%= image_tag @tool.tool_img.url(:tool_show) %>
		</div>
		<div class="col-lg-12">
			<%= image_tag @tool.tool_img2.url(:tool_show) %>
		</div>
	</div>



	<div class="col-lg-6">
		<h4>Category : <i>
			<% if @tool.toolcategory.level3? %>
			<%=  @tool.toolcategory.level1.to_s + " > " + @tool.toolcategory.level2.to_s +  " > " + @tool.toolcategory.level3.to_s %>
			<% elsif @tool.toolcategory.level2? %>
				<%=  @tool.toolcategory.level1.to_s + " > " + @tool.toolcategory.level2.to_s %>
				<% else %>
				<%=  @tool.toolcategory.level1.to_s %>
			<% end %></i>
		</h4><br>
		<h2><span class="label label-primary"><%= @tool.title %></span></h2><br>
		
		<h3><span class="xxxxxxxxxxxx"><%= @tool.short_desc %></span></h3><br>
		<h3>No:<span class="monospaced"><%= @tool.sku %></span></h3><br>

		<% if user_signed_in? %>
		<h3>Price:<span class="monospaced"> $<%= @tool.price %></span></h3><br>
		<% end %>

		<p><span class="description"><%= @tool.long_desc %></span></p><br>
		<h3><u>Specifications</u></h3><br>
		
		<% if @tool.brand? %>
			<div class="col-xs-6"><h4> Brand Name:</h4></div>
			<div class="col-xs-6"><h4><%= @tool.brand %></h4></div>
		<% end %>

		<% if @tool.weight? %>
			<div class="col-xs-6"><h4> Weight:</h4></div>
			<div class="col-xs-6"><h4><%= @tool.weight %></h4></div>
		<% end %>
		<% if @tool.height? %>
			<div class="col-xs-6"><h4> Height:</h4></div>
			<div class="col-xs-6"><h4><%= @tool.height %></h4></div>
		<% end %>

		<% if @tool.width? %>
			<div class="col-xs-6"><h4> Width:</h4></div>
			<div class="col-xs-6"><h4><%= @tool.width %></h4></div>
		<% end %>
		<% if @tool.color? %>
			<div class="col-xs-6"><h4> Color:</h4></div>
			<div class="col-xs-6"><h4><%= @tool.color %></h4></div>
		<% end %>

		<% if @tool.metal? %>
			<div class="col-xs-6"><h4> Metal:</h4></div>
			<div class="col-xs-6"><h4><%= @tool.metal %></h4></div>
		<% end %>
		<% if @tool.whatt? %>
			<div class="col-xs-6"><h4> Whatt:</h4></div>
			<div class="col-xs-6"><h4><%= @tool.whatt %></h4></div>
		<% end %>

		<% if @tool.measuringrange? %>
			<div class="col-xs-6"><h4> Measuring Range:</h4></div>
			<div class="col-xs-6"><h4><%= @tool.measuringrange %></h4></div>
		<% end %>
		<% if @tool.battery? %>
			<div class="col-xs-6"><h4> Battery:</h4></div>
			<div class="col-xs-6"><h4><%= @tool.battery %></h4></div>
		<% end %>
		<% if @tool.usedwith? %>
			<div class="col-xs-6"><h4> Used With:</h4></div>
			<div class="col-xs-6"><h4><%= @tool.usedwith %></h4></div>
		<% end %>

		<% if @tool.depth? %>
			<div class="col-xs-6"><h4> Depth:</h4></div>
			<div class="col-xs-6"><h4><%= @tool.depth %></h4></div>
		<% end %>

		<p>To order <a href="tel:18005551212">please call 1-800-555-1212</a></p>
	</div>




</div>