config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#home'
  get 'about', to:'welcome#about'

  get 'admin', to:'welcome#admin'

  get 'gemstones', to:'welcome#gemstone'

  resources :tools
  resources :toolcategories
  resources :fjewelries
  resources :findings

  resources :admgemstones

end

app/models/toolcategory.rb
class Toolcategory < ActiveRecord::Base
	has_many :tools
end

app/controllers/toolcategories_controller.rb
class ToolcategoriesController < ApplicationController

before_action :find_tool, only: [:edit, :update, :show, :destroy]
layout "applicationadmin"
	#def toolshome
	#	render :layout => "applicationtool"
	#end

	def index
		
		@toolcategories=Toolcategory.all.order("level1, level2, level3")
	
		
	end

	def show
		#Rails.logger.debug params.inspect
		
	end

	def new
		@toolcategory=Toolcategory.new
		
	end

	def create
		@toolcategory=Toolcategory.new(tool_params)
		
		if @toolcategory.save
			redirect_to toolcategories_path
		else
			render "new"
		end
	end

	def edit
		
	end

	def update
		
		if @toolcategory.update(tool_params)
			redirect_to toolcategories_path
		else
			render "edit"
		end
	end

	def destroy
		@toolcategory.destroy
		redirect_to toolcategories_path
	end

	private
	def tool_params
		params.require(:toolcategory).permit(:level1, :level2, :level3)
	end

	def find_tool
		@toolcategory=Toolcategory.find(params[:id])
	end

end

app/helpers/toolcategories_helper.rb
module ToolcategoriesHelper
end

app/views/toolcategories/_form.html.erb
<%=  simple_form_for @toolcategory, :html => { :multipart => true } do |f| %>

<%=  f.input :level1, label: "Main Category" %>
<%=  f.input :level2, label: "Sub Category" %>
<%=  f.input :level3, label: "SubOfSub Category" %>
<%=  f.button :submit, label: "Save" %>
<% end %>

app/views/toolcategories/edit.html.erb
<h2>Edit</h2>
<%= render "form" %>

app/views/toolcategories/index.html.erb
<div class="table-responsive" style="clear: right;">
  <table class="table table-hover table-condensed table-striped">
  	<thead>
  		<tr>
    		<th>ID</th>
    		<th>Main Category</th>
    		<th>Sub Category</th>
    		<th>Sub2 Category</th>
        <th colspan="2"></th>
  		</tr>
  	</thead>
	<tbody>
	<%  @toolcategories.each do |toolcategory| %>
	<tr>
			<td><%= toolcategory.id %></td>
			<td><%= toolcategory.level1 %></td>
			<td><%= toolcategory.level2 %></td>
			<td><%= toolcategory.level3 %></td>
		<td><%= link_to "Edit", edit_toolcategory_path(toolcategory), class: 'btn btn-warning btn-sm' %></td>
		<td><%= link_to "Delete", toolcategory_path(toolcategory), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-danger btn-sm' %></td>
	</tr>
	<% end %>
	</tbody>
  </table>
</div>
	
	
	<%= link_to "Add Tool Category", new_toolcategory_path, class: 'btn btn-success btn-md' %>
	<% if current_user.try(:admin?) %>
	<h3>Admin User Entered to This page</h3>
	<% end %>



				

app/views/toolcategories/new.html.erb
<h1>New Toolcategory Entry</h1>

<%=  render "form" %>