config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#home'
  get 'about', to:'welcome#about'

  get 'admin', to:'welcome#admin'

  get 'gemstones', to:'welcome#gemstone'

  resources :tools
  resources :toolcategories
  resources :fjewelries
  resources :findings

  resources :admgemstones

end

app/views/layouts/_headermenu.html.erb
<!--<header class="cd-header">-->
	<div>
	<nav id="nav" role="navigation"> <a href="#nav" title="Show navigation">Show navigation</a> <a href="#" title="Hide navigation">Hide navigation</a>

		<ul class="clearfix" style="margin-bottom:0px;">
		<!--<i class="material-icons">&#xE418;</i>-->
		<li class="logofake">
			<table>
			<tr>
			<td><a class="spline2l" href="#" ><span class="logotextfake"><b class="text2rem">E</b>uropean<br><em><b class="text2rem">D</b>esign</em></span></a></td>
			<td><a href="#"><%= image_tag('ic_rotate2x.png', :alt => 'Logo')%></a></td>
			</tr>
			</table>
		</li>	
		<li><a class="hide-menuitem" href="#"><b>Home</b></a></li>
		<li><%= link_to 'Finished <br id="skipbr"> Jewelry'.html_safe, fjewelries_path ,:class => "spline2" %></li>
		<!--<li><a class="spline2" href="#">Finished<br id="skipbr"> Jewelry</a></li>-->
		<li><%= link_to "Findings", findings_path %></li>
		<li><%= link_to "Gemstones", gemstones_path %></li>
		<li><a href="#">Diamonds</a></li>
		<li><%= link_to "Tools", tools_path %></li>
		<li class="srchli">	<!-- SEARCH BOX and Submit ICON -- Need to be modified at RoR -->
			<form class="navbar-form" role="search">
				<div class="input-group">
					<input type="text" class="form-control" placeholder="Search" name="srch-term" id="srch-term">
					<div class="input-group-btn">
						<button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
					</div>
				</div>
			</form>
		</li>

		<li><%= link_to '<span class="glyphicon glyphicon-user"></span> Sign Up'.html_safe, new_user_registration_path %></li>
		<% if user_signed_in? %>
			<li><%= link_to '<span class="glyphicon glyphicon-user"></span> Sign Out'.html_safe, destroy_user_session_path, method: :delete  %></li>
		<% else %>
			<li><%= link_to '<span class="glyphicon glyphicon-log-in"></span> Log In'.html_safe, new_user_session_path %></li>
		<% end %>

	</ul>
	</nav>
	</div>
	<!--</header>-->

app/views/layouts/_sidebarfinding.html.erb
<div id="sidebar-fj" class="container-fluid"> 
<!-- BEGIN SIDEBAR -->
	<div id="fj-filter" class="col-xs-2 col-lg-2">	
		 <div class="collapse navbar-collapse">

	<form action="/findings" method="get">

			<div>
				<ul>
				<li>
					<h4>Type</h4>
					<p></p>
					<div class="checkboxily">
						<%- Finding::FINDING_TYPES.each do |finding_type| -%>
			            <label for="fa1">  
			              <%= check_box_tag 'finding_type[]', finding_type, (params[:finding_type] && params[:finding_type].include?(finding_type)) %>
			              <em style="font-size: 1.4rem;"><%= finding_type.gsub(/\_/," ") %></em>
			            </label>
         				<%- end -%>	
					</div>
				</li>
				<li>
					<h4>Metal</h4>
					<p></p>
					<div class="checkboxily">
						<%- Finding::METALS.each do |metal| -%>
			            <label for="fb1">  
			              <%= check_box_tag 'metal[]', metal, (params[:metal] && params[:metal].include?(metal)) %>
			              <em style="font-size: 1.4rem;"><%= metal.gsub(/\_/," ") %></em>
			            </label>
         				<%- end -%>	
					</div>
				</li>	
				<li>
					<h4>Color</h4>
					<p></p>
					<div class="checkboxily">
						<%- Finding::COLORS.each do |color| -%>
			            <label for="fc1">  
			              <%= check_box_tag 'color[]', color, (params[:color] && params[:color].include?(color)) %>
			              <em style="font-size: 1.4rem;"><%= color.gsub(/\_/," ") %></em>
			            </label>
         				<%- end -%>	
					</div>
				</li>	
			
				</ul>
			</div>
	<button type='submit' class="btn btn-info" style="float:right;vertical-align:middle;color:#fff;width: 100%;background-color: red;">Search</button>
    <br>
  </form>

  
  <br>
		</div>
	</div>

app/views/layouts/_sidebarfjewelry.html.erb
<div id="sidebar-fj" class="container-fluid"> 
<!-- BEGIN SIDEBAR -->
	<div id="fj-filter" class="col-xs-2 col-lg-2">	
		 <div class="collapse navbar-collapse">

	<form action="/fjewelries" method="get">

			<div>
				<ul>
				<li>
					<h4>Type</h4>
					<p></p>
					<div class="checkboxily">
						<%- Fjewelry::JEWELRY_TYPES.each do |jewelry_type| -%>
			            <label for="fja1">  
			              <%= check_box_tag 'jewelry_type[]', jewelry_type, (params[:jewelry_type] && params[:jewelry_type].include?(jewelry_type)) %>
			              <em style="font-size: 1.4rem;"><%= jewelry_type.gsub(/\_/," ") %></em>
			            </label>
         				<%- end -%>	
					</div>
				</li>
				<li>
					<h4>Metal</h4>
					<p></p>
					<div class="checkboxily">
						<%- Fjewelry::METALS.each do |metal| -%>
			            <label for="fjb1">  
			              <%= check_box_tag 'metal[]', metal, (params[:metal] && params[:metal].include?(metal)) %>
			              <em style="font-size: 1.4rem;"><%= metal.gsub(/\_/," ") %></em>
			            </label>
         				<%- end -%>	
					</div>
				</li>	
				<li>
					<h4>Color</h4>
					<p></p>
					<div class="checkboxily">
						<%- Fjewelry::COLORS.each do |color| -%>
			            <label for="fjc1">  
			              <%= check_box_tag 'color[]', color, (params[:color] && params[:color].include?(color)) %>
			              <em style="font-size: 1.4rem;"><%= color.gsub(/\_/," ") %></em>
			            </label>
         				<%- end -%>	
					</div>
				</li>	
				<li>
					<h4>Stone</h4>
					<p></p>
					<div class="checkboxily">
						<%- Fjewelry::STONES.each do |stone| -%>
			            <label for="fjd1">  
			              <%= check_box_tag 'stone[]', stone, (params[:stone] && params[:stone].include?(stone)) %>
			              <em style="font-size: 1.4rem;"><%= stone.gsub(/\_/," ") %></em>
			            </label>
         				<%- end -%>	
					</div>
				</li>	
				</ul>
			</div>
	<button type='submit' class="btn btn-info" style="float:right;vertical-align:middle;color:#fff;width: 100%;background-color: red;">Search</button>
    <br>
  </form>

  
  <br>
		</div>
	</div>

app/views/layouts/_sidebartool.html.erb
<!-- BEGIN SIDEBAR -->
	<div class="accordion col-xs-2 col-lg-2">	
		  <div class="collapse navbar-collapse">
			<div class="opened-for-codepen">
			
				<% @toolcategories = Toolcategory.all.order("level1, level2, level3") %>
	    
				    <% exlevel1="" %>
				    <% exlevel2="" %>
				    <% exlevel3="" %>

				    <% @toolcategories.each do |tc| %>

				    	<% if tc.level1? and not(exlevel1 == tc.level1.to_s) %>
				      		
				      		<% if not(tc.level2?) %>
				      			<h1><%= link_to tc.level1, tools_path(tcat1: tc.level1, tcat2: nil, tcat3: nil) %></h1><div>
				      		<% else %>
				      			<h1><%= tc.level1 %></h1><div>
				      		<% end %>
				      	<% end %>


				      	<% if tc.level2? and not(exlevel2 == tc.level2.to_s and (exlevel3 == tc.level3.to_s)) %>
				      		<% if not(exlevel2 == tc.level2.to_s) %>
					      		<% if not(exlevel3=="") %>
					      			<% if not(tc.level3?) %>
					      				</div>
				      					<h2><%= link_to tc.level2, tools_path(tcat1: tc.level1, tcat2: tc.level2, tcat3: nil) %></h2><div>
				      				<% else %>
							      		</div>
							      		<h2><%= tc.level2 %></h2><div>
						      		<% end %>
					      		<% else %>
					      			<% if not(tc.level3?) %>
				      					<h2><%= link_to tc.level2, tools_path(tcat1: tc.level1, tcat2: tc.level2, tcat3: nil) %></h2><div>
				      				<% else %>
							      		<h2><%= tc.level2 %></h2><div>
						      		<% end %>
					      		<% end %>
					      	<% end %>
				      	<% else %>
				      		</div>
				      	<% end %>


				      	<% if tc.level3? and not((exlevel3 == tc.level3.to_s) and (exlevel2 == tc.level2.to_s)) %>
				      		<h3><%= link_to tc.level3, tools_path(tcat1: tc.level1, tcat2: tc.level2, tcat3: tc.level3) %></h3><div></div>
				      	<% else %>
				      		<% if tc.level2?  %>
				      			<% if not(exlevel3 == "") %>
				      				</div></div>
				      			<% else %>
				      				</div>
				      			<% end %>
				      		<% end %>
				      	<% end %>
				      	<% exlevel1=tc.level1.to_s %>
						<% exlevel2=tc.level2.to_s %>
				      	<% exlevel3=tc.level3.to_s %>

	   			<% end %>
					


						<!--
				  <h1>Abrasives</h1><div></div>
				  <h1>Benches & Accessories</h1><div></div>
				  <h1>Brushes</h1><div></div>
				  <h1>Buffs</h1><div></div>
				  <h1>Burs</h1><div></div>
				  <h1>Casting</h1><div></div>
				  <h1>Cleaners</h1><div></div>
				  <h1>Diamond Tools & Supplies</h1><div></div>
				  <h1>Equipments</h1>
				  <div>
					<h2>Laser Welder Evo Series</h2><div></div>
					<h2>Laser R Writer</h2>
					<div>
						<h3>A Class</h3><div></div>
						<h3>B Class</h3><div></div>
						<h3>C Class</h3><div></div>
					</div>
					<h2>Galloni Pressovac</h2><div></div>
					<h2>Gravograph Ring Cube</h2><div></div>
				  </div>
				  <h1>Drills</h1><div></div>
				  <h1>Files</h1><div></div>
				  <h1>Gauges</h1><div></div>
				  <h1>Hammers</h1><div></div>
				  <h1>Hand Forming</h1><div></div>
				  <h1>Lamps</h1><div></div>
				  <h1>Magnifiers & Glasses</h1><div></div>
				  <h1>Plating</h1><div></div>
				  <h1>Pilers & Cutters</h1><div></div>
				  <h1>Polishing</h1><div></div>
				  <h1>Ring Tools</h1><div></div>
				  <h1>Rolling Mills</h1><div></div>
				  <h1>Sawblades & Sawframes</h1><div></div>
				  <h1>Scale & Weights</h1><div></div>
				  <h1>Setting & Engraving</h1><div></div>
				  <h1>Soldering Tools</h1><div></div>
				  <h1>Store Supplies</h1><div></div>
				  <h1>Testing Tools</h1><div></div>
				  <h1>Tweezers</h1><div></div>
				  <h1>Watch Tools</h1><div></div>
				  <h1>Waxes</h1><div></div>	
				  -->	
			</div>
			</div>
		</div>
		

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= full_title(yield(:title)) %> | European Design</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  	<link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->
</head>
<body>
    <%= render 'layouts/headermenu' %>
    <!--
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    -->
    <%= yield %>

</body>
</html>

app/views/layouts/applicationadmin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= full_title(yield(:title)) %> | European Design</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  	<link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->
</head>
<body>
<div class="container-fluid" style="padding:0;">
<div class="well well-lg" style="background-color: red;color: #fff;margin-bottom:2rem;padding:1rem;font-size:3rem;">European Design Web Administration</div>
 <div class="row">
  <div class="col-xs-2 col-lg-2" style="background-color: mintcream;border:0px solid;border-radius:10px;padding:0px;">
  <ul class="nav nav-pills nav-stacked" style="padding:1rem;">
    <li role="presentation" class="active"><%= link_to 'Administration', admin_path %></li>
    <li role="presentation"><%= link_to 'Gemstones', admgemstones_path %></li>
    <li role="presentation"><a href="#">Diamonds</a></li>
    <li role="presentation"><a href="#">Finished Jewelry</a></li>
    <li role="presentation"><a href="#">Findings</a></li>
    <li role="presentation"><a href="#">Equipment</a></li>
    <li role="presentation"><%= link_to 'Tool Category', toolcategories_path %></li>
    <li role="presentation"><a href="#">Users</a></li>
    <li role="presentation"><%= link_to 'Client Home Page', root_path %></li>
  </ul>
  </div>
  <div class="col-xs-10 col-lg-10">


    <!--
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    -->
     <%= yield %>

  </div>
 </div>
</div>
   

</body>
</html>

app/views/layouts/applicationfinding.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= full_title(yield(:title)) %> | European Design</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->
</head>
<body>
    <%= render 'layouts/headermenu' %>
    <%= render 'layouts/sidebarfinding' %>
    <!--
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    -->
    <%= yield %>

</body>
</html>

app/views/layouts/applicationfindings.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= full_title(yield(:title)) %> | European Design</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  	<link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->
</head>
<body>
    <%= render 'layouts/headermenu' %>
    <%= render 'layouts/sidebarfindings' %>
    <!--
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    -->
    <%= yield %>

</body>
</html>

app/views/layouts/applicationfinishedjewelry.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= full_title(yield(:title)) %> | European Design</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  	<link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->
</head>
<body>
    <%= render 'layouts/headermenu' %>
    <%= render 'layouts/sidebarfinishedjewelry' %>
    <!--
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    -->
    <%= yield %>

</body>
</html>

app/views/layouts/applicationfjewelry.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= full_title(yield(:title)) %> | European Design</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  	<link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->
</head>
<body>
    <%= render 'layouts/headermenu' %>
    <%= render 'layouts/sidebarfjewelry' %>
    <!--
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    -->
    <%= yield %>

</body>
</html>

app/views/layouts/applicationtool.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= full_title(yield(:title)) %> | European Design</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  	<link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->
</head>
<body>
    <%= render 'layouts/headermenu' %>
    <!-- BEGIN CONTENT -->
    <div id="content-tools" class="container-fluid"> 
    <%= render 'layouts/sidebartool' %>
    <!--
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    -->
    <%= yield %>
    </div>
<script>
var headers = ["H1","H2","H3","H4","H5","H6"];

$(".accordion").click(function(e) {
  var target = e.target,
      name = target.nodeName.toUpperCase();
  
  if($.inArray(name,headers) > -1) {
    var subItem = $(target).next();
    
    //slideUp all elements (except target) at current depth or greater
    var depth = $(subItem).parents().length;
    var allAtDepth = $(".accordion p, .accordion div").filter(function() {
      if($(this).parents().length >= depth && this !== subItem.get(0)) {
        return true; 
      }
    });
    $(allAtDepth).slideUp("fast");
    
    //slideToggle target content and adjust bottom border if necessary
    subItem.slideToggle("fast",function() {
        $(".accordion :visible:last").css("border-radius","0 0 10px 10px");
    });
    $(target).css({"border-bottom-right-radius":"0", "border-bottom-left-radius":"0"});
  }
});
</script>
</body>
</html>